"""empty message

Revision ID: 2abf39dd62e3
Revises: 49d4a2a1189a
Create Date: 2013-12-30 14:33:12.829750

"""

# revision identifiers, used by Alembic.
revision = '2abf39dd62e3'
down_revision = '49d4a2a1189a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('sex', sa.String(length=1), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'sex')
    ### end Alembic commands ###
