"""empty message

Revision ID: 49d4a2a1189a
Revises: 6eba9e6850b
Create Date: 2013-12-30 14:15:54.511435

"""

# revision identifiers, used by Alembic.
revision = '49d4a2a1189a'
down_revision = '6eba9e6850b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('mobile_platform', sa.String(length=1000), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistics', 'mobile_platform')
    ### end Alembic commands ###
