"""empty message

Revision ID: 6eba9e6850b
Revises: None
Create Date: 2013-12-30 12:54:34.270392

"""

# revision identifiers, used by Alembic.
revision = '6eba9e6850b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('foot_size', sa.Integer(), nullable=True),
    sa.Column('eye_color', sa.String(length=1000), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('year_started_working', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name','last_name', name='unique_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    ### end Alembic commands ###
